apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: argo-webhook
  labels:
    app: argo-webhook
webhooks:
- name:  argo-webhook.argo.svc.cluster.local
  objectSelector:
    matchLabels:    
      hello: "true"
  rules:
  - apiGroups:   ["argoproj.io"]
    apiVersions: ["v1alpha1"]
    operations:  ["CREATE", "UPDATE", "DELETE"]
    resources:   ["cronworkflows"]
    #scope:       "Cluster" # or Namespaced
    scope:       "Namespaced"
  clientConfig:
    #caBundle: |
    #  LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURqRENDQW5RQ0NRQ0pwa0tCN2ppOThEQU5CZ2txaGtpRzl3MEJBUXNGQURDQmh6RUxNQWtHQTFVRUJoTUMKV0ZneEVqQVFCZ05WQkFnTUNWTjBZWFJsVG1GdFpURVJNQThHQTFVRUJ3d0lRMmwwZVU1aGJXVXhGREFTQmdOVgpCQW9NQzBOdmJYQmhibmxPWVcxbE1Sc3dHUVlEVlFRTERCSkRiMjF3WVc1NVUyVmpkR2x2Yms1aGJXVXhIakFjCkJnTlZCQU1NRldGeVoyOHRkMlZpYUc5dmF5NWhjbWR2TG5OMll6QWVGdzB5TlRBeE1UTXlNalE0TVROYUZ3MHoKTlRBeE1URXlNalE0TVROYU1JR0hNUXN3Q1FZRFZRUUdFd0pZV0RFU01CQUdBMVVFQ0F3SlUzUmhkR1ZPWVcxbApNUkV3RHdZRFZRUUhEQWhEYVhSNVRtRnRaVEVVTUJJR0ExVUVDZ3dMUTI5dGNHRnVlVTVoYldVeEd6QVpCZ05WCkJBc01Fa052YlhCaGJubFRaV04wYVc5dVRtRnRaVEVlTUJ3R0ExVUVBd3dWWVhKbmJ5MTNaV0pvYjI5ckxtRnkKWjI4dWMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTJxb0h5Ujd4eVZHOApFY2JySS92S0lpbFc5WHEvUm1memIrbnhsc05ZNkh3UGNuNXRtYkZvUTJqcXgzUkhVdDBiOXYvbmlBZHc1SW1WClhNOTVuNVZHZnQ4Q0NoVmNPcHBCcTV3YWF0WWtLMmZ0cHkrWUhzUWt5QkJPUHBhMXJtS2Z3TUVVNEc1MGhwbG8KU25kcW52eVBnUkFDbG4wcitkZ1N5UDM5cHQ2eGgyZ1d5S0VqT3pwaXBDQTVNeTdQa3IveTBQemRuYlgwK1pCZgpGVEZSbXF6VkJ5cEhBMXVSWTJ0bjloUTBQbG8wVG1ZV0FXU1BPdXhmZnpUTUVsMWg3eTIyWVFiN3lvU0VMV0JkCk4yMU1QN3ZiQld5bmNWbk9jd1JUVlU2SXArOEJYemJZNzR4d1d1SkFvaFBHNzFlME1OOTM5cjE5QTI1V3gxTFoKVXRoZnJNNEtWd0lEQVFBQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXRJT0l1VVVlNDRRYk5PaUhoY1ZxcgphQkw3ZEZheGJPRDlqTXp5OGNGS3dydDkrdGsrTWJnaVV6TDh0R0EyOVFWTCtHRWZ4VFNjcWV0bmNGWFRJeFN3CjZQWXI3b0MyVmt0WlUzemlaY1QvK1QyR3A0dUhybXVYSjZlRTdZa2pyMnM4UURkSitIWEhLRzh4cWxRWXZHYkIKTHBFTUMwaUQzT04zWXZOS2N3ZUw1c2lzRjRRZFNGckxpUW9Id3pYaUpzaVdyOGllYXU5NE5EVWZoZzZPVXcrYgoyZktNUW1salkrM2tQdHlBcVAxM1BBV2kyZmdmSlV3Ym1IQmlTamdiTjBjSlBOdjhyU3ZpbG8xZlovUHg0MXA5CitOYjFoY3Z2QWZXVVQwcGpWeks1OXVwVEJXM201dTFsbnRKK2drMzFDc21JL3pSWXI0NmorVWl5NnZtMTJDZnEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      namespace: "argo"
      name: "argo-webhook"  
      path: /mutate
  admissionReviewVersions: ["v1"]
  failurePolicy: "Fail"
  sideEffects: None
  timeoutSeconds: 10
