apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "argo-webhook.colinbruner.com"
webhooks:
- name: "argo-webhook.colinbruner.com"
  objectSelector:
    matchLabels:    
      hello: "true"
  rules:
  - apiGroups:   ["argoproj.io"]
    apiVersions: ["v1alpha1"]
    operations:  ["CREATE", "UPDATE"]
    resources:   ["cronworkflows"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: "argo"
      name: "argo-webhook"  
      path: /mutate
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 10